#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Script: metrics
#
# Description: this python script collects metrics about linux server:
#                     - OS release
#                     - CPU metrics
#                     - Memory metrics
#                     - Uptime
#                     - Disk usage
#
# Requirement(s):     linux, python, psutils (library) | https://psutil.readthedocs.io/
#
# Changelog:          * 12/18/2020: Igor Petrenko
#                     - Initial release
#
# Usage:
#                     ./metrics os
#                     ./metrics cpu
#                     ./metrics memory
#                     ./metrics uptime
#                     ./metrics disk
import psutil
import datetime
import platform
import sys
from sys import argv

def os():
    # OS release
    print("System:",platform.system())
    print("Platform:",platform.release())
    print("machine:",platform.machine())

def uptime():
    # System boot time converted to human readable format
    print("System boot time:",datetime.datetime.fromtimestamp(psutil.boot_time()).strftime("%Y-%m-%d %H:%M:%S"))

def disk():
    # Disk usage metrics for '/'
    disk_usage_total = psutil.disk_usage('/').total
    print("disk_usage for / total:",disk_usage_total)
    disk_usage_used = psutil.disk_usage('/').used
    print("disk_usage for / used:",disk_usage_used)
    disk_usage_free = psutil.disk_usage('/').free
    print("disk_usage for / free:",disk_usage_free)
    disk_usage_percent = psutil.disk_usage('/').percent
    print("disk_usage for / percent:",disk_usage_percent,"%")

def cpu():
    # CPU metrics
    print("Number of cores in system:", psutil.cpu_count())
    print("Number of physical cores in system:", psutil.cpu_count(logical=False))
    print("Number of logical cores in system:", psutil.cpu_count(logical=True))
    cpu_user = psutil.cpu_times().user
    print("system.cpu.user:",cpu_user)
    cpu_system = psutil.cpu_times().system
    print("system.cpu.system:",cpu_system)
    cpu_idle = psutil.cpu_times().idle
    print("system.cpu.idle:",cpu_idle)
    cpu_nice = psutil.cpu_times().nice
    print("system.cpu.nice:",cpu_nice)
    cpu_iowait = psutil.cpu_times().iowait
    print("system.cpu.iowait:",cpu_iowait)
    cpu_irq = psutil.cpu_times().irq
    print("system.cpu.irq:",cpu_irq)
    cpu_softirq = psutil.cpu_times().softirq
    print("system.cpu.softirq:",cpu_softirq)
    cpu_steal = psutil.cpu_times().steal
    print("system.cpu.steal:",cpu_steal)
    cpu_guest = psutil.cpu_times().guest
    print("system.cpu.guest:",cpu_guest)

def memory():
    # Memory metrics
    virtual_total = psutil.virtual_memory().total
    print("virtual total:",virtual_total)
    virtual_available = psutil.virtual_memory().available
    print("virtual available:",virtual_available)
    virtual_used = psutil.virtual_memory().used
    print("virtual used:",virtual_used)
    virtual_free = psutil.virtual_memory().free
    print("virtual free:",virtual_free)
    virtual_active = psutil.virtual_memory().active
    print("virtual active:",virtual_active)
    virtual_inactive = psutil.virtual_memory().inactive
    print("virtual inactive:",virtual_inactive)
    virtual_buffers = psutil.virtual_memory().buffers
    print("virtual buffers:",virtual_buffers)
    virtual_cached = psutil.virtual_memory().cached
    print("virtual cached:",virtual_cached)
    virtual_shared = psutil.virtual_memory().shared
    print("virtual shared:",virtual_shared)

if __name__ == "__main__":
    if len(sys.argv) > 1 and len(sys.argv) < 3:
        if sys.argv[1] == "os":
            os()
        if sys.argv[1] == "cpu":
            cpu()
        if sys.argv[1] == "memory":
            memory()
        if sys.argv[1] == "disk":
            disk()
        if sys.argv[1] == "uptime":
            uptime()
    else:
        sys.stderr.write("""Please enter os|cpu|memory|disk|uptime\n""")
        sys.exit
